Avoid TypeError in Safari
I'm seeing this TypeError in Safari from a call to
Uint8ClampedArray.from:
TypeError: TypedArray.from requires its this argument subclass a
TypedArray constructor

The error might be caused by my Babel configuration, but I'm seeing if
replacing the call to Uint8ClampedArray.from will avoid the error.